In [1]:
# Dependencies & set up
import pandas as pd
import numpy as np

In [2]:
# Getting fata from csv files
d1 = 'blockchain_11-05-2021.csv'
d2 = 'blockchain_11-06-2021.csv'
d3 = 'blockchain_11-07-2021.csv'
d4 = 'blockchain_11-08-2021.csv'
d5 = 'blockchain_11-09-2021.csv'
d6 = 'blockchain_11-10-2021.csv'
d7 = 'blockchain_11-11-2021.csv'
d8 = 'blockchain_11-12-2021.csv'
d9 = 'blockchain_11-13-2021.csv'
d10 = 'blockchain_11-15-2021.csv'
d11 = 'blockchain_11-16-2021.csv'
d12 = 'blockchain_11-17-2021.csv'
d13 = 'blockchain_11-18-2021.csv'
d14 = 'blockchain_11-19-2021.csv'
d15 = 'blockchain_11-20-2021.csv'
d16 = 'blockchain_11-21-2021.csv'
d17 = 'blockchain_11-22-2021.csv'
d18 = 'blockchain_11-23-2021.csv'
d19 = 'blockchain_11-25-2021.csv'
d20 = 'blockchain_11-26-2021.csv'
d21 = 'blockchain_11-29-2021.csv'
d22 = 'blockchain_11-30-2021.csv'
d23 = 'blockchain_12-01-2021.csv'
d24 = 'blockchain_12-01-2021.csv'
d25 = 'blockchain_12-02-2021.csv'
d26 = 'blockchain_12-04-2021.csv'
d27 = 'blockchain_12-05-2021.csv'
d28 = 'blockchain_12-06-2021.csv'
d29 = 'blockchain_12-07-2021.csv'
d30 = 'blockchain_12-08-2021.csv'
d31 = 'blockchain_12-09-2021.csv'
d32 = 'blockchain_12-10-2021.csv'
d33 = 'blockchain_12-11-2021.csv'
d34 = 'blockchain_12-12-2021.csv'
d35 = 'blockchain_12-13-2021.csv'
d36 = 'blockchain_12-14-2021.csv'
d37 = 'blockchain_12-15-2021.csv'
# d38 = 'blockchain_12-16-2021.csv'

In [3]:
# Creating a list based on csv
bdata = [d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37]

In [4]:
# Creating empty list
b_data = []

# Loop for appending csv into a data frame
for file in bdata:
    b_data.append(pd.read_csv(file))

# Concat all dataframes
bdata = pd.concat(b_data, sort=False)
bdata

,symbol,price_24h,volume_24h,last_trade_price,difference,date
0,XLM-EUR,0.318070,57185.591182,0.311000,0.0,11-05-2021
1,ALGO-BTC,0.000031,223.638922,0.000030,0.0,11-05-2021
2,EFI-USDT,1.480000,3414.004740,1.499000,0.0,11-05-2021
3,XLM-BTC,0.000000,0.000000,0.000006,0.0,11-05-2021
4,USDC-GBP,0.744700,50000.000000,0.744700,0.0,11-05-2021
...,...,...,...,...,...,...
99,BTC-USDT,47981.970000,29.902171,48874.890000,NaN,12-15-2021
100,ETH-USDT,3821.530000,1527.808925,4037.160000,NaN,12-15-2021
101,MATIC-USD,1.910000,3211.759040,2.164000,NaN,12-15-2021
102,SUSHI-USD,5.934000,148.358389,5.780000,NaN,12-15-2021
103,DAI-USD,1.000200,314.783000,1.000000,NaN,12-15-2021

In [5]:
# filling n/a with 0
bdata.fillna(0, inplace=True)

In [6]:
bdata['last_trade_price'].dtypes

dtype('float64')

In [7]:
# bdata.loc[bdata.symbol == 'XLM-EUR', :]

In [8]:
# getting list of symbols
df= bdata['symbol']
df = df.drop_duplicates()
len(df)

104

In [9]:
# creating a loop for filling the 'difference' column using loc in the symbol column then append into a dataframe
d=[]
for i in df:
    c = pd.DataFrame(bdata.loc[bdata.symbol == i, :])
    c['difference']=(c.last_trade_price.diff(1)).round(decimals=5)
    c['difference'] = c['difference'].astype(float)


    c[['%_difference']] = c[['difference']].pct_change().round(decimals=5)
    c['%_difference'] = c['%_difference'].astype(float)
    d=pd.DataFrame(d.append(c))

In [10]:
c

,symbol,price_24h,volume_24h,last_trade_price,difference,date,%_difference
103,CEUR-EUR,0.00,0.000000,0.00,NaN,11-11-2021,NaN
103,CEUR-EUR,0.00,0.000000,0.00,0.00,11-12-2021,NaN
103,CEUR-EUR,0.00,0.000000,0.00,0.00,11-13-2021,NaN
103,CEUR-EUR,0.00,0.000000,0.00,0.00,11-15-2021,NaN
103,CEUR-EUR,1.00,1602.427328,1.02,1.02,11-16-2021,inf
103,CEUR-EUR,1.03,2485.044999,1.03,0.01,11-17-2021,-0.9902
103,CEUR-EUR,1.03,0.000000,1.03,0.00,11-18-2021,-1.0000
56,CEUR-EUR,1.00,4.330435,1.00,-0.03,11-19-2021,-inf
56,CEUR-EUR,1.00,0.000000,1.00,0.00,11-20-2021,-1.0000
56,CEUR-EUR,1.00,0.000000,1.00,0.00,11-21-2021,NaN
56,CEUR-EUR,1.00,48.950050,1.00,0.00,11-22-2021,NaN
56,CEUR-EUR,1.00,0.000000,1.00,0.00,11-23-2021,NaN
56,CEUR-EUR,0.99,3.995005,0.99,-0.01,11-25-2021,-inf
56,CEUR-EUR,1.01,18.441480,1.01,0.02,11-26-2021,-3.0000
56,CEUR-EUR,1.00,1426.591890,1.07,0.06,11-29-2021,2.0000
56,CEUR-EUR,1.07,0.000000,1.07,0.00,11-30-2021,-1.0000
56,CEUR-EUR,1.00,7.000000,1.00,-0.07,12-01-2021,-inf
56,CEUR-EUR,1.00,7.000000,1.00,0.00,12-01-2021,-1.0000
56,CEUR-EUR,1.02,0.000000,1.00,0.00,12-02-2021,NaN
56,CEUR-EUR,1.04,0.000000,1.04,0.04,12-04-2021,inf
56,CEUR-EUR,1.04,0.000000,1.04,0.00,12-05-2021,-1.0000
56,CEUR-EUR,1.04,30002.261000,1.05,0.01,12-06-2021,inf
56,CEUR-EUR,1.00,1999.027841,1.06,0.01,12-07-2021,0.0000
56,CEUR-EUR,1.06,0.000000,1.06,0.00,12-08-2021,-1.0000
56,CEUR-EUR,1.06,0.000000,1.06,0.00,12-09-2021,NaN
56,CEUR-EUR,1.02,84.839743,1.03,-0.03,12-10-2021,-inf
56,CEUR-EUR,1.03,0.000000,1.03,0.00,12-11-2021,-1.0000
56,CEUR-EUR,1.03,0.000000,1.03,0.00,12-12-2021,NaN
56,CEUR-EUR,1.03,0.000000,1.03,0.00,12-13-2021,NaN
56,CEUR-EUR,0.98,35.434464,0.98,-0.05,12-14-2021,-inf
56,CEUR-EUR,1.01,28.713000,1.02,0.04,12-15-2021,-1.8000

In [11]:
# filling n/a with 0
d.fillna(0, inplace=True)
d.reset_index(drop=True, inplace=True)

In [12]:
d

,symbol,price_24h,volume_24h,last_trade_price,difference,date,%_difference
0,ALGO-BTC,0.000031,223.638922,0.00003,0.00,11-05-2021,0.0
1,ALGO-BTC,0.000030,156.156380,0.00003,-0.00,11-06-2021,0.0
2,ALGO-BTC,0.000030,0.000000,0.00003,0.00,11-07-2021,0.0
3,ALGO-BTC,0.000028,1707.329433,0.00003,0.00,11-08-2021,0.0
4,ALGO-BTC,0.000029,204.832462,0.00003,-0.00,11-09-2021,0.0
...,...,...,...,...,...,...,...
3794,CEUR-EUR,1.030000,0.000000,1.03000,0.00,12-11-2021,-1.0
3795,CEUR-EUR,1.030000,0.000000,1.03000,0.00,12-12-2021,0.0
3796,CEUR-EUR,1.030000,0.000000,1.03000,0.00,12-13-2021,0.0
3797,CEUR-EUR,0.980000,35.434464,0.98000,-0.05,12-14-2021,-inf
3798,CEUR-EUR,1.010000,28.713000,1.02000,0.04,12-15-2021,-1.8

In [13]:
d = d.replace([np.inf, -np.inf], 0)

In [14]:
d.to_csv('out_.csv')